# In this notebook we are goint to cover fundamentals using TensorFlow
https://www.youtube.com/watch?v=tpCFfeUEGs8&list=PL6vjgQ2-qJFfU2vF6-lG9DlSa4tROkzt9&index=4

More specifically, we are goint to cover:
* into to tensors
* getting information from tensors
* manipulating tensors
* tensors and numpy
* Using @tf.function (a way to speedup regular python functions)
* using GPU with TensorFlow or TPUs
* exercises

# Introduction to Tensors

In [2]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.8.2


In [3]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
# checkt he number of dimensions of a tensor
scalar.ndim

0

In [5]:
# Create a vector
vector = tf.constant([10,10])

In [6]:
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [7]:
# check the dimension of our vector
vector.ndim

1

In [8]:
# Create a matrix ( has more than 1 dimension)

In [9]:
matrix = tf.constant([[10,7],
                    [7,10]])

In [10]:
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [11]:
matrix.ndim

2

In [12]:
# Create another matrix
another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [8., 9.]], dtype=tf.float16)  #specify the data by dtype param

In [13]:
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [14]:
another_matrix.ndim

2

In [15]:
# Lets ceate a tensor
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[7,8,9],
                       [10,11,12]],
                      [[13,14,15],
                       [16,17,18]]])

In [16]:
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [17]:
tensor.ndim

3

### Creating tensors with tf.Variable

In [18]:
# create the same tensor with tf.Variable as above
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [19]:
# Let's try change one of the elements in our changeable tensor
changeable_tensor[0] = 7

TypeError: ignored

In [ ]:
# How about we try .assign()
changeable_tensor[0].assign(7)
changeable_tensor

In [ ]:
# Let's try change our unchangeable tensor
unchangeable_tensor[0] = 7

In [ ]:
unchangeable_tensor[0].assign(7)

## Creating random tensors
filled with random numbers

In [ ]:
# crete two random tensors (but the same)
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))

random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))

In [ ]:
random_1, random_2, random_1 == random_2

### Shuffle the order of elements in a tensor

In [ ]:
# valuable when loading samples to nn
not_shuffled = tf.constant([[10., 7.],
                              [3., 2.],
                              [8., 9.]])

In [ ]:
not_shuffled.ndim

In [ ]:
not_shuffled

In [ ]:
tf.random.shuffle(not_shuffled) # shuffle around first dimension , elements stay in order

### Other ways to make tensors

In [ ]:
tf.ones([10,7])

In [ ]:
tf.zeros([10,7])

In [ ]:
# You can also turn numpy arrays into tensors


main differencee between numpy arrays and tensorflow tensts is that tensors can be run on a GPU computing

In [ ]:
import numpy as np
numpy_A = np.arange(1,25, dtype=np.int32) #create a Numpy array between 1 and 25
numpy_A

# X = tf.constant(some_matrix) # capital for matrix or tensor
# y = tf.constant(vector) # non


In [ ]:
A = tf.constant(numpy_A)
A

In [ ]:
A = tf.constant(numpy_A, shape=(2,3,4))
B = tf.constant(numpy_A)
A,B

# elements of shape must adds up to the original number of elements of array

### Getting information from tensors

* shape
* rank
* axis or dimension
* size

In [ ]:
# Create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros([2,3,4,5])
rank_4_tensor

In [ ]:
# Get various attrobutes of our tensor
print("Datatype of every element:", rank_4_tensor.dtype)

In [ ]:
print("Number of dimensions (rank):", rank_4_tensor.ndim)

In [ ]:
print("Shape of tensor:", rank_4_tensor)

In [ ]:
print("Elements along the 0 axis:",rank_4_tensor.shape[0])

In [ ]:
print("Total number of elements in our tensor:", tf.size(rank_4_tensor).numpy)

In [ ]:
print("Elements along the last axis:",rank_4_tensor.shape[-1])

### Indexing tensors

tensors can be indexed just like Python lists

In [ ]:
# get the first 2 elements of each dimensions
rank_4_tensor[:2, :2, :2, :2]

In [ ]:
some_list = [1, 2, 3, 4]

In [ ]:
some_list[:2]

In [ ]:
# Get the first element from each dimension from each index except for the final one

In [ ]:
rank_4_tensor[:1, :1, :1, :]

2hod 10 min video

In [ ]:
# Create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[10, 7],
                            [3,4]])

In [ ]:
rank_2_tensor.shape, rank_2_tensor.ndim

In [ ]:
rank_2_tensor

In [ ]:

# Get the last item of each of our rank 2 tensor
rank_2_tensor[:,-1]

In [ ]:
# Add in extra dimension to rank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

In [ ]:
# another possible approach
rank_3_tensor = rank_2_tensor[:, :, tf.newaxis]

In [ ]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1)  # -1 means we want to expand on the last axis

In [ ]:
tf.expand_dims(rank_2_tensor, axis=0) #expand the 0-axis

### Manipulating tensors (tensor operations)
2h 18min

In [ ]:
# add values to a tensor
tensor = tf.constant([[10,7],
                      [3,4]])

In [ ]:
tensor + 1

In [ ]:
# Original tensor is unchanger

In [ ]:
tensor

In [ ]:
# Multiplication 
tensor * 10

In [ ]:
# We can use the tensorflow builtin function too
tf.multiply(tensor, 10)

 Matrix multiplication 
 2h 24min

In [ ]:
# Matrix multiplication in tensorflow
print(tensor)

In [ ]:
tf.matmul(tensor, tensor)

In [ ]:

# Matrix multiplication with python operator "@"
tensor @ tensor

In [21]:
X = tf.constant([[1,2],
                 [3,4],
                 [5,6]])
Y = tf.constant([[7,8],
                 [9,10],
                 [11,12]])
X,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
# Try to matrix multiply tensors of same shape
tf.matmul(X,Y)

Two rules our tensors( or matrices ) need to fulfil

1. The inner dimensions must match
2. The resulting matrix has the shape of the inner dimensions

In [ ]:
# Let's change the shape of Y
tf.reshape(Y, shape=(2,3))

In [ ]:
# Try to multiply X by reshaped
X @ tf.reshape(Y, shape=(2,3))

In [ ]:
X.shape, tf.reshape(Y, shape=(2,3)).shape   # the rule 1 is satisfied, inner dimensions are the same

In [ ]:
tf.matmul(X, tf.reshape(Y, shape=(2,3)))

In [ ]:
# try chaneg the shape of X instead Y
tf.matmul(tf.reshape(X, shape=(2,3)), Y)

In [ ]:
# output depends on shape on tensors - difference between transpose and reshape - transpose flip the axis

In [ ]:
# Can do the same with transpose
X, tf.transpose(X), tf.reshape(X, shape=(2,3))

**The dot product**

matrix multiplication is also referred to as the dot product
2:49:50
https://www.mathsisfun.com/algebra/matrix-multiplying.html

You can perform matrix multiplication using:

* tf.matmul()
* tf.tensordot()

In [22]:
# Perform the dot product on X and Y (requires X or Y to be transposed)
tf.tensordot(tf.transpose(X),Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [24]:
# Perform matrix multiplication between X and Y (transposed)
tf.tensordot(X,tf.transpose(Y), axes=1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [25]:
# Perform matrix multiplication between X and Y (transposed)
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [26]:
# Perform matrix multiplication between X and Y (reshaped)
tf.matmul(X, tf.reshape(Y, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [28]:
# Check the values of Y, reshape Y and transposed Y
print("Normal Y:")
print(Y,"\n")
print("Y reshaped to (2,3)")
print(tf.reshape(Y, (2,3)), "\n")

print("Y transposed:")
print(tf.transpose(Y))

Normal Y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped to (2,3)
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed:
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


3:00:59